language: android
android:
  components:
  - tools
  - build-tools-26.0.1
  - platform-tools
  - android-26
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-25
  - extra
  - addon
  - sys-img-armeabi-v7a-android-26
licenses:
- android-sdk-license-.+
- .+
before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
before_script:
  - export TERM=dumb
  - curl -L http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin -O
  - chmod u+x android-ndk-r10e-linux-x86_64.bin
  - ./android-ndk-r10e-linux-x86_64.bin > /dev/null
  - rm android-ndk-r10e-linux-x86_64.bin
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r10e
  - export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME"
  - export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64"
  - export PATH=$PATH:${ANDROID_NDK_HOME}
  - env
  - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
- ./gradlew build jacocoTestReport
after_success:
    - bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: dHgfatkY1Q0Sfhm+JHejrsKe6nWRzmcLZuSsHObKbBKmKWNaSDtpVL8q6QsOfeK0wCOVTWVp/vhNejajxcybGxE6zELfjR8EDOWwtJbvNY52ARxblWZPp6HhZk+jDMmqmLUfrQpZaF9dUDGxKmoWudl6PRivDQIK29bS/uQupRdz7HZWEr7uTPHQKbxRpeFFoL7KSNLgAUypxRnqA/3rZ1wHMnQDt0qONbDgpHLpICPjylQqIQBkY14UnPh/Tu0n5F9LOLqQquTINPg7Bt3lJzVD1fjZ95UehBU8vACST4P75WvuFJ2yiGAYpchs6P9ZEooFe1YzINEBlLm3ytvWfAnqeoSUD/+Dx0AYPkRSZyPg26f4qsqkalPCR/4Lr3oit0nKYqETY5+Rt+tvsqmSk73X/k+e7FN8D4FeUo4CCJsl5F+ReGwJzJP1hkTw43nx3BmopzqokDBq+Pbdb7RH8QkAS/ynhDzoeCDxqCx8CCTswVhrdYFQ+hnoHdmA78Ifw0wTVO9GToki4pF45zp3XJvL3oDGYho5myrqPGZfZtVTsaZDBrvjMAqsZMiEZ4FZlfLZkLXMC3PYLUbWWK4HARfWANAneIPaKk3hyA+NcRVDsY44W5jzmboCGMu8QdhhFmrqWrpMDFq55iHge+7k7pyTym5uIXo26pQvwuiNhZI=
  - secure: PmvVWbZGTuLe6umhMoO1WWIXSe0Oux/7L3ZO/cyOaCj9tjyzMolLloCracXOaBr6amIwKYEDLk2vALVeNscQGtmPKcthHAdJzwEeApgkjtE09SGkLKB0KuHjmC5o3WE6wGntXm9AnJBqdRX2rzYVDVbjqT/fPoPtfNQ1rubqYlBBXM/8wYZqwml2PgJqsfse27LP8fUZQkUTux+791JlcqMQOdbxuxc+tyPwlwOipMbBsu2lKqbD/iVd2cvM+PwhXTbjVIA+76pTN5u1zDzKKP7lZyLrGiQled526hlBDZ3Fi2Tfx71juHDm9I/E/ORCxwNzpUXKiIVeSJJD6pt/ojVmlSWAheFY5VGOjYP7OhzsN4N5LDOR/ej8ueYrLfiu/tNiXO6ToQ5P6Rohf5xHBAI5rNeV7L9ZrDCvfJN4jIywQSvN15rCtQXpnB3rIxpqWsCQGlEV5kE5BHgpOVscO/261gJii+mB7UVaZCmOl4B/ZW+SAE4KE7Rwq+fFgHM1mBH7nbHGaDcRah1b2Re6fBdHRZ2Lrn8Azy/Hhh0D0tps+V0DCchIsW14bcVQXG1dfMwQRbP+gGNXa5GWxksTJoJxl/S9wAQ9tUG7FE/VXnLl3985JlGXCxS5GPpFzbvJ3fNZ+tNUfy3pis9zqOKkfmxdegtb/q+CKtrChQavM9M=
  - secure: A+O+63MKXOvtahogL9jfeE1qvGCeofwqvL6f9L6RCWxX1yX+Na2KnW+wL5Hw42R/xkxUqlBTwsXwhGjZzBTWIMhYIuzijDbaurLMOmb/eLHbkQCDh5WrELarTWIK7qcmbjq0PvAeA6gynsFVMA+BctJ7H0Z1CiG92Y+1clwgVuQSAFqWIX0TiBrTQm81Nz8ptR1f9AAr8FiqQMgxUwh0AJObv1p00nWMrQor2N4HN92QC4tasFI5e5ng5Nw+eOr0IizXJKWqy2NGChW9RgrPcihXEJ/pzQ5bMSx8RcrojEj8bPT0gqDlTd1/Nsps8PkoicE9P0fJycUCA0n7Z7WJKb1tNoq/cu1HpMjf+vO6Tbaj4cdOHbH0Wk5DlBaruvwBYJ5y2Mocm+CItjeFMJgW9+gLI2ZZx3t8EkYBXB6ZdqR8u9mfSqtULGRRk1fipJp16eofzPPc48Fh3WXCVIYueBc9FRtrDLj1CmEEEEPdCJOpZyLiRh/8hJeoYlRaNuFqWnfe0MaEXYA74Qx+A00LlkQHMisQJTh4yfrFPIxgEIierfMVE5lF7nvx0brVXFm88uISXylJ073fOC9G3mejKdLqdtT6zY9t3nV+8wdaqeFxw9uDDuVQ82iA5TQ5aW1YMD1wdz5ZDdrLK4c6F/43Mj6vZVTVzijJ37WRGm894iY=
  - secure: B4WhVaVgxiPX0VSIq1YraRdockJOf4L2ThhdIUNtT4Bccxn11lIrytvyl7IsmaCJIKXpHipogii4pGmMAgGYyUjGDaHGepdX4Q74bsoUmczPSvLrhwJ1SLhKq62W3WXRUB2r9ST87C3oH8gaVXTKdS9/dsChFRrl/F1nqitkKs6YZBl/EHnYstoVivppioVTGjDThAKVjymO4ydvwmOH3hefyvMuAslLDEjjbLMfU8+TTKnrobf+gmFvr4Jaekp++z13GNQcqhyJl1nOLOTyudyixlMU2jdd75lUHuoTPwz4z1JQVKbR2Gu+xfcbvuHByuWlH2/BtoBdqu8g603GCbUlOS0vYGNYB72KpfOdCYoQrvhA0KnjajLD57FCXW9t3/ygC9MMsqSl82ftHsHKE2HNNU8VPFpDoev0wTvMrYXp4JuNW25rE8fqg3fI61BwhDfCDnx55uUqJPsWCEafvlbLfAmZY50aFLY+WScxIoi2+XOrcbICBdWywudjqgpGxR/5TEiyDJFxhwYIG0eVpVd5y+iJ0NmRZTYPMZlkObzgtWsveELAV03kQdP4o5q8VYMUNA+3KLr6Y5LAyEz9MMcOPJc6s3T2DXSrJl/kyrCf90d1zqFXFeMqVD3IWnpK8g1fCfkJTQdvi4fsZwGxggW4LJ/6dT0sqFLad/NRgYU=
