language: android
android:
  components:
  - tools
  - build-tools-26.0.1
  - platform-tools
  - android-26
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-25
licenses:
- android-sdk-license-.+
- .+
before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
script:
- ./gradlew build
env:
  global:
  - secure: VJlKHojVBdIousaaGg15uxR/M2Ot83Xnf/vaQSXjVHW8akwV4cTKG2EXwdliLvrFVBY6VpI/fTmz2flYfVlsDKKbeblz8SJGud2bdK/IEhNzHrbsdRsHPb2ciTg8FPM/VQkfIRIcXtxr32oBOOoJknhfAxbbS/kzAPtg4M/YtwgJTeGskGIfkCZ2w0fksWqNByZnBanok/TFIUdh3jf5SN8LGfKCmmzD4hE/q+7/rNbMulO0ZONVkWHmuyO51EJ8ZI/NjTfxhGjKUHfbI92RwWmTQrIuR1h1n8PGG71gQPlR+ey0FNuDUopXfdqMeUu5r8jr03OGgsQBBTeJd+d9x9T8kAqdJWhH+c0fW/gpESshLpBRHZ/F6X3x5M0CMQh3A5ZTHlM6ZWjBta5JjLNkRr8CH1Q0oeiQ5EtOgUi5LZfTh5SHTnO5UcghbM+WCMahZXYODUAweANaazd03uCiNXH17PkjkYcZZosLH6QDFTAHdTqbilOcKXe+N3WIdptYhPzCh89Rtt0mGswELpNBAxmq8qXveY9RRztSq1R6ADW1o7apr4H7bDp/nJgNa37YuB9U6ZiCBPB83lvc/jUR5Nj5FWyV0/Zeawq7fXRRAoG6jbotnyfcec9doifFQ7lxliDCjMSR8xO9DouTA8KUfGloDsjcjIkyAcvNz9fpTBU=
  - secure: T2sXhmIhBa4amaQ/eShwhDyKM6dplgXoRPIK4r6qdtDnQwYmVbhBWzxBWbHD4sVD/afijMES3mWamSjQiba64/hH8w/qEPvq+MxDcR/sMNx60xYmZSDikAKKFdV+2vxh/t88XhVsDTYtjRL0W3nsVwUONGuZSOvwffBOFLVLohdHC2YEqEdxC8u9U/x/843ErMHALOQXBPij7Ba+JCIUPL3JtqX6alWKXlgIQC+p2Po1N+XHqmUB7URMpF8H29QZ4nUgdyqiYS+2njYVxM//wGGx95znkTGE/bK7M7PhYJuw5lTlwU7xS5YtUw4lDCdUNIj7YCwwlImGq0VJu3fZkPFOxCAGpnW7Q2+9hSXjsOk8GVaxFz67b2WVXY9owUBLvmVh7pPz+yBhc7CW7U5Wm/UHMOZ41Twng9W8GOFWgw4Oow5Q1KMgDwSnhzhoL7uQjuXS6rG6Sa2ujvgrGJ3/RzYfY6nKNx4OJAGvsOMp+wGL6NwqPsl79Q7LnhUyiEJYcrVV6GsSzJOukhxNldlCLlJpT+GcNPkytHKQlRXU/2KroW/3h5hwy+a4C0Ps1daVkYkdzzWnsRbTcDnHNALpSgpOuHqxiuyP+nBO8BLJLf+/qIQ61+BO1/nN/+ReaThDi7PuTvbR/zBEA3wT4sZ0rxVxBDCtjyRNiEXyIWVpvyI=
  - secure: caGtXXPMEBqiH+5p415/UxIl7XYNBRa7g1qC9F8rLtediN4fzB6CVEHudu4mVV3CRMrEv7VKExG/w63bgyZbxsyvoVCbdMSVUu+/VEzDU9m11C+tW0yWPwAn0GY9dqABxls6gEDLZtaluWszYRP4kvBhrSEU2mHGG5XY/dZh9Dyv281RMJpYgr6fXY7s+X/myGpkWqEVZny9x6aJPCH8yzudSTb7W1tjwnqp9S7iekFoacTYRKVYVKnyUDiJtJoJc/WNtWsfOIghCM7BMX3NEtGzhByLP12XB0nkzdCu93+uAGD6gbMxL3CRoJ3PLrhqbhna3/MdckaCtpjnP8GDKfiqgoiAYUKRkoWZHuGxAW0jnu/+Z4HKd2wCms4cvtnfMGe3Ur4SBGxCFh1KFp7sG5rWDcCq3pGUE4kLiRLbMaqnEQ/i0REE/QI2XswxMKEydLQT1Fr5nDKUUwILHTvwaenROT15G9cSshnUFbFfNvDpCznQP+3gC3bqeWN7v/e5GjZ0gh8GsHIGjbcnWa+NiHk1Hp16fO3dntFZzZGwuGkEiOQ2JzQr/v4qnh5x23WrKyFAVIpzsSLCm5M86UGw9Q+Gzd33zK/IouQfCjjicEsp782/sIM+H7ze/xpW4V83RvRXfgMABzAwOSjPZf2JGTpvOXsHiZYF4F3cqW4ujWs=
